package com.mapswitch.world;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.mapswitch.MapSwitchMod;
import com.mapswitch.map.MapManager;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.level.storage.LevelResource;

import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class MapsBootstrapManager {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final String NAMESPACE = MapSwitchMod.MOD_ID;

    public record BootstrapResult(boolean changed, Path datapackPath, Path worldRoot) {
    }

    public BootstrapResult ensureBootstrap(MinecraftServer server, Path mapsRoot, List<String> maps) {
        try {
            Path datapacksRoot = server.getWorldPath(LevelResource.DATAPACK_DIR);
            Path worldRoot = datapacksRoot.getParent();
            if (worldRoot == null) {
                return new BootstrapResult(false, datapacksRoot.resolve("mapswitch-generated"), datapacksRoot);
            }

            Path datapackRoot = datapacksRoot.resolve("mapswitch-generated");
            boolean changed = false;
            changed |= writePackMcmeta(datapackRoot.resolve("pack.mcmeta"));

            for (String map : maps) {
                String mapId = MapManager.toIdentifierPath(map);
                changed |= writeDimensionJson(datapackRoot, mapId, "overworld", "minecraft:overworld", "minecraft:overworld", "minecraft:overworld");
                changed |= writeDimensionJson(datapackRoot, mapId, "nether", "minecraft:the_nether", "minecraft:nether", "minecraft:nether");
                changed |= writeEndDimensionJson(datapackRoot, mapId);
                changed |= importMapData(worldRoot, mapsRoot, map, mapId);
            }

            return new BootstrapResult(changed, datapackRoot, worldRoot);
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to bootstrap map datapack", ex);
        }
    }

    private boolean writePackMcmeta(Path file) throws IOException {
        Files.createDirectories(file.getParent());
        Map<String, Object> root = new LinkedHashMap<>();
        Map<String, Object> pack = new LinkedHashMap<>();
        pack.put("description", "Generated by MapSwitch");
        pack.put("pack_format", 94);
        root.put("pack", pack);
        return writeJsonIfChanged(file, root);
    }

    private boolean writeDimensionJson(Path datapackRoot, String map, String suffix, String type, String settings, String preset) throws IOException {
        Path file = datapackRoot.resolve("data").resolve(NAMESPACE).resolve("dimension").resolve(map + "_" + suffix + ".json");
        Files.createDirectories(file.getParent());

        Map<String, Object> root = new LinkedHashMap<>();
        root.put("type", type);

        Map<String, Object> generator = new LinkedHashMap<>();
        generator.put("type", "minecraft:noise");
        generator.put("settings", settings);
        Map<String, Object> biomeSource = new LinkedHashMap<>();
        biomeSource.put("type", "minecraft:multi_noise");
        biomeSource.put("preset", preset);
        generator.put("biome_source", biomeSource);
        root.put("generator", generator);

        return writeJsonIfChanged(file, root);
    }

    private boolean writeEndDimensionJson(Path datapackRoot, String map) throws IOException {
        Path file = datapackRoot.resolve("data").resolve(NAMESPACE).resolve("dimension").resolve(map + "_end.json");
        Files.createDirectories(file.getParent());

        Map<String, Object> root = new LinkedHashMap<>();
        root.put("type", "minecraft:the_end");
        Map<String, Object> generator = new LinkedHashMap<>();
        generator.put("type", "minecraft:noise");
        generator.put("settings", "minecraft:end");
        Map<String, Object> biomeSource = new LinkedHashMap<>();
        biomeSource.put("type", "minecraft:the_end");
        generator.put("biome_source", biomeSource);
        root.put("generator", generator);
        return writeJsonIfChanged(file, root);
    }

    private boolean importMapData(Path worldRoot, Path mapsRoot, String rawMapName, String mapId) throws IOException {
        Path mapRoot = mapsRoot.resolve(rawMapName);
        if (Files.notExists(mapRoot)) {
            return false;
        }

        Path dimensionsRoot = worldRoot.resolve("dimensions").resolve(NAMESPACE);
        Path overworldTarget = dimensionsRoot.resolve(mapId + "_overworld");
        Path netherTarget = dimensionsRoot.resolve(mapId + "_nether");
        Path endTarget = dimensionsRoot.resolve(mapId + "_end");

        boolean changed = false;
        changed |= copyIfMissing(mapRoot.resolve("region"), overworldTarget.resolve("region"));
        changed |= copyIfMissing(mapRoot.resolve("entities"), overworldTarget.resolve("entities"));
        changed |= copyIfMissing(mapRoot.resolve("poi"), overworldTarget.resolve("poi"));
        changed |= copyIfMissing(mapRoot.resolve("DIM-1").resolve("region"), netherTarget.resolve("region"));
        changed |= copyIfMissing(mapRoot.resolve("DIM-1").resolve("entities"), netherTarget.resolve("entities"));
        changed |= copyIfMissing(mapRoot.resolve("DIM-1").resolve("poi"), netherTarget.resolve("poi"));
        changed |= copyIfMissing(mapRoot.resolve("DIM1").resolve("region"), endTarget.resolve("region"));
        changed |= copyIfMissing(mapRoot.resolve("DIM1").resolve("entities"), endTarget.resolve("entities"));
        changed |= copyIfMissing(mapRoot.resolve("DIM1").resolve("poi"), endTarget.resolve("poi"));
        return changed;
    }

    private boolean copyIfMissing(Path source, Path target) throws IOException {
        if (Files.notExists(source) || Files.exists(target)) {
            return false;
        }
        Files.createDirectories(target.getParent());
        copyRecursive(source, target);
        return true;
    }

    private void copyRecursive(Path source, Path target) throws IOException {
        if (Files.isDirectory(source)) {
            Files.createDirectories(target);
            try (var stream = Files.list(source)) {
                for (Path child : stream.toList()) {
                    copyRecursive(child, target.resolve(child.getFileName().toString()));
                }
            }
            return;
        }
        Files.createDirectories(target.getParent());
        Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
    }

    private boolean writeJsonIfChanged(Path file, Object data) throws IOException {
        String next = GSON.toJson(data);
        if (Files.exists(file)) {
            String current = Files.readString(file);
            if (current.equals(next)) {
                return false;
            }
        }
        try (Writer writer = Files.newBufferedWriter(file)) {
            writer.write(next);
        }
        return true;
    }
}



